### ISSUE TITLE
The auto-generated trial license can onverride an existing instance

### ISSUE THREAD

**Issue by gdelhumeau** [xwikisas/xwiki-pro#22] opened 2021-05-03 10:21 UTC
Hello, I have a problem with an XWiki Pro and the licensing app (I don't know on which project I should open this issue).

I have a valid license that I install manually in XWiki (using `$services.licensing.licensor.addLicense($license)`), before installing XWiki PRO. But when XWiki PRO is installed, it automatically generates a TRIAL license, and override my own license. When I go to XWiki Administration > Extensions > License I can only see the TRIAL license.

I think you should skip the genration of the trial if there is already a valid license.

**Comment by oanalavinia** [comment] 2021-05-04 14:27
This issue is related to the licensing application, so I raised an issue there [#98](https://github.com/xwikisas/application-licensing/issues/98)

**Comment by mflorea** [comment] 2021-05-05 07:55
@oanalavinia if this is true:

> I have a valid license that I install manually in XWiki (using $services.licensing.licensor.addLicense($license)), before installing XWiki PRO. 

then the free license should be already present in the XWiki instance so no need to download it, right? So either the license wasn't fully installed locally or the code that checks for an existing license has a problem. Would be good if you can try to reproduce the problem:

* generate a free license for some paid app on store (for your XWiki instance id)
* install the license on your XWiki instance using @gdelhumeau 's script
* install the paid app

**Comment by gdelhumeau** [comment] 2021-05-05 08:05
My script:
```
{{velocity}}
#macro (returnAndReportError $message)
  #set ($discard = $response.setStatus(500))
  $message
  $services.logging.getLogger("REST Executor").error($message)
#end
#####################################
## Save License
#####################################
#set ($license = '{{ LICENSE }}')
#try('addLicenseException')
  #set ($licenseAdded = $services.licensing.licensor.addLicense($license))
#end
#if ($licenseAdded && "$!addLicenseException" == '')
  OK
#else
  #returnAndReportError("Failed to add license data [$license] on the instance. #if($addLicenseException)Exception: $!{exceptiontool.getStackTrace($addLicenseException)}#end")
#end
{{/velocity}}
```

Replace `{{ LICENSE }}` by your license, as a string.

**Comment by oanalavinia** [comment] 2021-06-04 09:14
The problem was fixed in the dependency application that caused it and can be applied through an upgrade to Application Licensing [1.18](https://github.com/xwikisas/application-licensing/milestone/28?closed=1)
Note that this release increases the minimal supported version of XWiki to 10.11

**Closed by oanalavinia** 2021-06-04 09:14 UTC
